In [1]:
import pandas as pd
import zipfile # it is used for reading the zip file without extrating
import numpy as np
import matplotlib.pyplot as plt

In [3]:

with zipfile.ZipFile("matches.zip") as Z:
    with Z.open("matches_Spain.json") as f:
        matches_df = pd.read_json(f)

In [4]:
matches_df

,status,roundId,gameweek,teamsData,seasonId,dateutc,winner,venue,wyId,label,date,referees,duration,competitionId
0,Played,4406122,38,"{'676': {'scoreET': 0, 'coachId': 92894, 'side...",181144,2018-05-20 18:45:00,676,Camp Nou,2565922,"Barcelona - Real Sociedad, 1 - 0","May 20, 2018 at 8:45:00 PM GMT+2","[{'refereeId': 398931, 'role': 'referee'}, {'r...",Regular,795
1,Played,4406122,38,"{'679': {'scoreET': 0, 'coachId': 3427, 'side'...",181144,2018-05-20 16:30:00,0,Estadio Wanda Metropolitano,2565925,"Atl\u00e9tico Madrid - Eibar, 2 - 2","May 20, 2018 at 6:30:00 PM GMT+2","[{'refereeId': 395056, 'role': 'referee'}, {'r...",Regular,795
2,Played,4406122,38,"{'691': {'scoreET': 0, 'coachId': 444778, 'sid...",181144,2018-05-20 14:15:00,691,San Mam\u00e9s Barria,2565919,"Athletic Club - Espanyol, 0 - 1","May 20, 2018 at 4:15:00 PM GMT+2","[{'refereeId': 384957, 'role': 'referee'}, {'r...",Regular,795
3,Played,4406122,38,"{'674': {'scoreET': 0, 'coachId': 210074, 'sid...",181144,2018-05-20 10:00:00,674,Estadio de Mestalla,2565924,"Valencia - Deportivo La Coru\u00f1a, 2 - 1","May 20, 2018 at 12:00:00 PM GMT+2","[{'refereeId': 398913, 'role': 'referee'}, {'r...",Regular,795
4,Played,4406122,38,"{'675': {'scoreET': 0, 'coachId': 275283, 'sid...",181144,2018-05-19 18:45:00,0,Estadio de la Cer\u00e1mica,2565927,"Villarreal - Real Madrid, 2 - 2","May 19, 2018 at 8:45:00 PM GMT+2","[{'refereeId': 395085, 'role': 'referee'}, {'r...",Regular,795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,Played,4406122,1,"{'691': {'scoreET': 0, 'coachId': 169425, 'sid...",181144,2017-08-19 20:15:00,0,Estadio Ram\u00f3n S\u00e1nchez Pizju\u00e1n,2565552,"Sevilla - Espanyol, 1 - 1","August 19, 2017 at 10:15:00 PM GMT+2","[{'refereeId': 378950, 'role': 'referee'}, {'r...",Regular,795
376,Played,4406122,1,"{'756': {'scoreET': 0, 'coachId': 167044, 'sid...",181144,2017-08-19 18:15:00,0,Estadi Municipal de Montilivi,2565551,"Girona - Atl\u00e9tico Madrid, 2 - 2","August 19, 2017 at 8:15:00 PM GMT+2","[{'refereeId': 378994, 'role': 'referee'}, {'r...",Regular,795
377,Played,4406122,1,"{'692': {'scoreET': 0, 'coachId': 3880, 'side'...",181144,2017-08-19 16:15:00,687,Estadio de Bala\u00eddos,2565549,"Celta de Vigo - Real Sociedad, 2 - 3","August 19, 2017 at 6:15:00 PM GMT+2","[{'refereeId': 384946, 'role': 'referee'}, {'r...",Regular,795
378,Played,4406122,1,"{'674': {'scoreET': 0, 'coachId': 210074, 'sid...",181144,2017-08-18 20:15:00,674,Estadio de Mestalla,2565556,"Valencia - Las Palmas, 1 - 0","August 18, 2017 at 10:15:00 PM GMT+2","[{'refereeId': 381927, 'role': 'referee'}, {'r...",Regular,795
379,Played,4406122,1,"{'696': {'scoreET': 0, 'coachId': 117648, 'sid...",181144,2017-08-18 18:15:00,712,Estadio Municipal de Butarque,2565557,"Legan\u00e9s - Deportivo Alav\u00e9s, 1 - 0","August 18, 2017 at 8:15:00 PM GMT+2","[{'refereeId': 398931, 'role': 'referee'}, {'r...",Regular,795

In [5]:
#weekly points

point_data = list()
for i in range(len(matches_df)):
    gameweek = matches_df.iloc[i].gameweek# iloc is used for the locating data in a data frame
    label = matches_df.iloc[i].label
    match_id = matches_df.iloc[i].wyId
    
    score = label.split(",")[1]
    b = score.split("-")
    c = [int(i) for i in b]
    diff = c[0] - c[1]
    
    [[home_team, away_team], [home_score, away_score]] = [[o.strip() for o in s.split('-')] for s in label.split(',')]# here we have converted the label column into a nested list, od home team/away team . HOme score and Away score 
    home_score = int(home_score)
    away_score = int(away_score)
    if home_score > away_score:# we have identified the winner /looser and Draw
        home_point = 3
        away_point = 0
    if away_score > home_score:
        away_point = 3
        home_point = 0
    if away_score == home_score:
        home_point = 1
        away_point = 1
    point_data.append([gameweek, home_team, home_point,label,match_id,diff]) #here we have summarize the team with week and point all together
    point_data.append([gameweek, away_team, away_point,label,match_id,-diff])
point_df = pd.DataFrame(point_data, columns=['gameweek', 'team', 'point','label','matchId','tempgd'])

In [6]:
weeks = np.sort(point_df.gameweek.unique())
teams = point_df.team.unique()
points_cp = pd.DataFrame([])

for team in teams:
    t1 = point_df[point_df.team == team]
    cumP = {}
    cumgd ={}
    t1 = t1.sort_values(by=['gameweek'])
    for week in weeks:
        if week == 1:
            cumP[week] = int(t1[t1.gameweek == 1]['point'])
            cumgd[week] = int(t1[t1.gameweek == 1]['tempgd'])
        else:
            cumP[week] = int(t1[t1.gameweek == week]['point']) + cumP.get(week -1) 
            cumgd[week] = int(t1[t1.gameweek == week]['tempgd']) + cumgd.get(week -1)
    
    t1['cummPoints'] = t1.apply(lambda x : cumP.get(x.gameweek),axis =1)
    t1['gd'] = t1.apply(lambda x : cumgd.get(x.gameweek),axis =1)
#     print(t1)
    points_cp = points_cp.append(t1)

In [7]:
weekly_points = pd.DataFrame()
for week in weeks:
    t1 = points_cp[points_cp.gameweek == week]
    t2 =t1.sort_values(by=['cummPoints','gd'],ascending=False)
    t2['rank'] = [i for i in range(1,t2.shape[0]+1)]
    weekly_points = weekly_points.append(t2)

In [8]:
weekly_points

,gameweek,team,point,label,matchId,tempgd,cummPoints,gd,rank
745,1,Real Madrid,3,"Deportivo La Coru\u00f1a - Real Madrid, 0 - 3",2565555,3,3,3,1
746,1,Barcelona,3,"Barcelona - Real Betis, 2 - 0",2565554,2,3,2,2
755,1,Real Sociedad,3,"Celta de Vigo - Real Sociedad, 2 - 3",2565549,1,3,1,3
741,1,Eibar,3,"M\u00e1laga - Eibar, 0 - 1",2565553,1,3,1,4
756,1,Valencia,3,"Valencia - Las Palmas, 1 - 0",2565556,1,3,1,5
...,...,...,...,...,...,...,...,...,...
4,38,Athletic Club,0,"Athletic Club - Espanyol, 0 - 1",2565919,-1,43,-8,16
16,38,Legan\u00e9s,3,"Legan\u00e9s - Real Betis, 3 - 2",2565926,1,43,-17,17
7,38,Deportivo La Coru\u00f1a,0,"Valencia - Deportivo La Coru\u00f1a, 2 - 1",2565924,-1,29,-38,18
14,38,Las Palmas,0,"Las Palmas - Girona, 1 - 2",2565923,-1,22,-50,19
12,38,M\u00e1laga,0,"M\u00e1laga - Getafe, 0 - 1",2565921,-1,20,-37,20

In [9]:
# for cur_index, item in enumerate(team):
#     if item == 'Atl\\u00e9tico Madrid':
#         team[cur_index]='Atletico Madrid'
#     if item == 'Deportivo La Coru\\u00f1a':
#         team[cur_index]='Deportivo La Coruna'
#     if item == 'Deportivo Alav\\u00e9s':
#         team[cur_index]='Deportivo Alaves'
#     if item == 'M\\u00e1laga':
#         team[cur_index]='Malaga'
#     if item == 'Legan\\u00e9s':
#         team[cur_index]='Leganes'

# for cur_index, item in enumerate(home_team):
#     if item == 'Atl\\u00e9tico Madrid':
#         home_team[cur_index]='Atletico Madrid'
#     if item == 'Deportivo La Coru\\u00f1a':
#         home_team[cur_index]='Deportivo La Coruna'
#     if item == 'Deportivo Alav\\u00e9s':
#         home_team[cur_index]='Deportivo Alaves'
#     if item == 'M\\u00e1laga':
#         home_team[cur_index]='Malaga'
#     if item == 'Legan\\u00e9s':
#         home_team[cur_index]='Leganes'
    
# for cur_index, item in enumerate(away_team):
#     if item == 'Atl\\u00e9tico Madrid':
#         away_team[cur_index]='Atletico Madrid'
#     if item == 'Deportivo La Coru\\u00f1a':
#         away_team[cur_index]='Deportivo La Coruna'
#     if item == 'Deportivo Alav\\u00e9s':
#         away_team[cur_index]='Deportivo Alaves'
#     if item == 'M\\u00e1laga':
#         away_team[cur_index]='Malaga'
#     if item == 'Legan\\u00e9s':
#         away_team[cur_index]='Leganes'

In [10]:
weekly_points.

,gameweek,team,point,label,matchId,tempgd,cummPoints,gd,rank
745,1,Real Madrid,3,"Deportivo La Coru\u00f1a - Real Madrid, 0 - 3",2565555,3,3,3,1
746,1,Barcelona,3,"Barcelona - Real Betis, 2 - 0",2565554,2,3,2,2
755,1,Real Sociedad,3,"Celta de Vigo - Real Sociedad, 2 - 3",2565549,1,3,1,3
741,1,Eibar,3,"M\u00e1laga - Eibar, 0 - 1",2565553,1,3,1,4
756,1,Valencia,3,"Valencia - Las Palmas, 1 - 0",2565556,1,3,1,5
...,...,...,...,...,...,...,...,...,...
4,38,Athletic Club,0,"Athletic Club - Espanyol, 0 - 1",2565919,-1,43,-8,16
16,38,Legan\u00e9s,3,"Legan\u00e9s - Real Betis, 3 - 2",2565926,1,43,-17,17
7,38,Deportivo La Coru\u00f1a,0,"Valencia - Deportivo La Coru\u00f1a, 2 - 1",2565924,-1,29,-38,18
14,38,Las Palmas,0,"Las Palmas - Girona, 1 - 2",2565923,-1,22,-50,19
12,38,M\u00e1laga,0,"M\u00e1laga - Getafe, 0 - 1",2565921,-1,20,-37,20

In [13]:
weekly_points.shape

(760, 9)

In [71]:
updated_df = pd.DataFrame(columns = weekly_points.columns)
for index,row in weekly_points.iterrows():
#     print(row.team.split(",")[0].split("-"))
#     print(correct_team_name(row.team))
    row.team = correct_team_name(row.team)
    row.label = correct_labels(row.label)
    updated_df = updated_df.append(row)

In [75]:
updated_df = updated_df.sort_values(by=["team",'gameweek'])

In [76]:
updated_df

,gameweek,team,point,label,matchId,tempgd,cummPoints,gd,rank
748,1,Athletic Club,1,"Athletic Club-Getafe, 0 - 0",2565550,0,1,0,9
727,2,Athletic Club,3,"Eibar-Athletic Club, 0 - 1",2565567,1,4,1,6
706,3,Athletic Club,3,"Athletic Club-Girona, 2 - 0",2565574,2,7,3,4
685,4,Athletic Club,0,"Las Palmas-Athletic Club, 1 - 0",2565578,-1,7,2,6
672,5,Athletic Club,0,"Athletic Club-Atletico Madrid, 1 - 2",2565589,-1,7,1,9
...,...,...,...,...,...,...,...,...,...
43,34,Villarreal,0,"Barcelona-Villarreal, 5 - 1",2565884,-4,51,1,6
74,35,Villarreal,3,"Villarreal-Celta de Vigo, 4 - 1",2565888,3,54,4,6
54,36,Villarreal,3,"Villarreal-Valencia, 1 - 0",2565901,1,57,5,6
31,37,Villarreal,3,"Deportivo La Coruna-Villarreal, 2 - 4",2565911,2,60,7,5
8,38,Villarreal,1,"Villarreal-Real Madrid, 2 - 2",2565927,0,61,7,5

In [77]:
updated_df.to_csv("spainLeague.csv")

In [49]:
# set(updated_df.label.tolist())
# .split(",").split("-").unique()

In [51]:
set([correct_team_name(y) for y in x.split(",")[0].split("-") for x in updated_df.label])

NameError: name 'x' is not defined

In [61]:
",".join([team_test(x) for x in updated_df.label])

TypeError: sequence item 0: expected str instance, list found

In [63]:
list2d = ([team_test(x) for x in updated_df.label])

In [65]:
import itertools
# list2d = [[1,2,3], [4,5,6], [7], [8,9]]
merged = list(itertools.chain(*list2d))
set(merged)

{' Athletic Club',
 ' Atl\\u00e9tico Madrid',
 ' Barcelona',
 ' Celta de Vigo',
 ' Deportivo Alav\\u00e9s',
 ' Deportivo La Coru\\u00f1a',
 ' Eibar',
 ' Espanyol',
 ' Getafe',
 ' Girona',
 ' Las Palmas',
 ' Legan\\u00e9s',
 ' Levante',
 ' M\\u00e1laga',
 ' Real Betis',
 ' Real Madrid',
 ' Real Sociedad',
 ' Sevilla',
 ' Valencia',
 ' Villarreal',
 'Athletic Club ',
 'Atl\\u00e9tico Madrid ',
 'Barcelona ',
 'Celta de Vigo ',
 'Deportivo Alav\\u00e9s ',
 'Deportivo La Coru\\u00f1a ',
 'Eibar ',
 'Espanyol ',
 'Getafe ',
 'Girona ',
 'Las Palmas ',
 'Legan\\u00e9s ',
 'Levante ',
 'M\\u00e1laga ',
 'Real Betis ',
 'Real Madrid ',
 'Real Sociedad ',
 'Sevilla ',
 'Valencia ',
 'Villarreal '}

In [59]:
def team_test(x):
    t = x.split(",")
    return [correct_team_name(x) for x in t[0].split("-")]

In [68]:
def correct_team_name(name):
    team=name.strip()
    if (team == 'Atl\\u00e9tico Madrid') :
        team='Atletico Madrid'
    if team == 'Deportivo La Coru\\u00f1a':
        team='Deportivo La Coruna'
    if team == 'Deportivo Alav\\u00e9s':
        team='Deportivo Alaves'
    if team == 'M\\u00e1laga':
        team='Malaga'
    if team == 'Legan\\u00e9s':
        team='Leganes'
        
    return team

In [39]:
def correct_labels(label):
    temp = label.split(",")
    temp[0] = "-".join([correct_team_name(x) for x in temp[0].split("-")])
    return ",".join(temp)

In [26]:
s ="M\u00e1laga - Getafe, 0 - 1"

In [27]:
s

'MÃ¡laga - Getafe, 0 - 1'

In [29]:
a = s.split(",")

['MÃ¡laga - Getafe', ' 0 - 1']

In [31]:
a = s.split(",")

In [35]:
a[0] = "-".join([correct_team_name(x) for x in a[0].split("-")])

In [37]:
",".join(a)

'MÃ¡laga - Getafe, 0 - 1'